import type { KeyboardGuideMap } from "./types";

export const keyboardGuideMap: KeyboardGuideMap = {
  a: { keyPosition: "Home row - A", finger: "Left pinky" },
  b: { keyPosition: "Bottom row - B", finger: "Left index" },
  c: { keyPosition: "Bottom row - C", finger: "Left middle" },
  d: { keyPosition: "Home row - D", finger: "Left middle" },
  e: { keyPosition: "Top row - E", finger: "Left middle" },
  f: { keyPosition: "Home row - F", finger: "Left index" },
  g: { keyPosition: "Home row - G", finger: "Left index" },
  h: { keyPosition: "Home row - H", finger: "Right index" },
  i: { keyPosition: "Top row - I", finger: "Right middle" },
  j: { keyPosition: "Home row - J", finger: "Right index" },
  k: { keyPosition: "Home row - K", finger: "Right middle" },
  l: { keyPosition: "Home row - L", finger: "Right ring" },
  m: { keyPosition: "Bottom row - M", finger: "Right index" },
  n: { keyPosition: "Bottom row - N", finger: "Right index" },
  o: { keyPosition: "Top row - O", finger: "Right ring" },
  p: { keyPosition: "Top row - P", finger: "Right pinky" },
  q: { keyPosition: "Top row - Q", finger: "Left pinky" },
  r: { keyPosition: "Top row - R", finger: "Left index" },
  s: { keyPosition: "Home row - S", finger: "Left ring" },
  t: { keyPosition: "Top row - T", finger: "Left index" },
  u: { keyPosition: "Top row - U", finger: "Right index" },
  v: { keyPosition: "Bottom row - V", finger: "Left index" },
  w: { keyPosition: "Top row - W", finger: "Left ring" },
  x: { keyPosition: "Bottom row - X", finger: "Left ring" },
  y: { keyPosition: "Top row - Y", finger: "Right index" },
  z: { keyPosition: "Bottom row - Z", finger: "Left pinky" }
};
